#!/bin/bash
# Script hướng dẫn Git workflow

echo "🌿 Git Workflow Guide"
echo "====================="
echo ""

echo "📋 Branch Structure:"
echo "  master   → Production (live system)"
echo "  staging  → Test/Staging environment"
echo "  develop  → Development (integration)"
echo "  feature/* → Feature branches"
echo "  bugfix/*  → Bug fix branches"
echo "  hotfix/*  → Hotfix for production"
echo ""

echo "🔄 Typical Workflow:"
echo ""
echo "1. Create feature branch:"
echo "   ./scripts/git/create_branch.sh my-feature develop feature"
echo ""
echo "2. Develop and commit:"
echo "   git add ."
echo "   git commit -m 'Add new feature'"
echo ""
echo "3. Push feature branch:"
echo "   ./scripts/git/push.sh feature/my-feature"
echo ""
echo "4. Merge to develop:"
echo "   git checkout develop"
echo "   git merge feature/my-feature"
echo ""
echo "5. Merge to staging (for testing):"
echo "   ./scripts/git/merge_to_staging.sh develop"
echo ""
echo "6. Test on staging, then merge to production:"
echo "   ./scripts/git/merge_to_production.sh staging"
echo ""
echo "7. Deploy to production:"
echo "   ./scripts/release/deploy.sh production"
echo ""

echo "🚨 Hotfix Workflow:"
echo ""
echo "1. Create hotfix from master:"
echo "   ./scripts/git/create_branch.sh critical-fix master hotfix"
echo ""
echo "2. Fix and test:"
echo "   # Make fixes"
echo "   git commit -m 'Fix critical issue'"
echo ""
echo "3. Merge to master and staging:"
echo "   ./scripts/git/merge_to_production.sh hotfix/critical-fix"
echo "   ./scripts/git/merge_to_staging.sh hotfix/critical-fix"
echo ""

echo "📊 Current Status:"
echo ""
git branch -a 2>/dev/null || echo "Not a git repository"
echo ""
CURRENT=$(git branch --show-current 2>/dev/null || echo "unknown")
echo "Current branch: $CURRENT"

